#!/bin/bash -e
#
# QEMU network interface configuration script for OIM. This utility needs to
# be run as normal user and depends on sudo.
#
# Copyright (c) 2006-2011 Linux Foundation
# Copyright (c) 2018 Intel Corporation
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

usage() {
	echo "$(basename $0) <number of nodes>"
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi


for i in $(seq 0 $(($1 - 1))); do
    TAP=oimtap$i
    sudo ip tuntap add $TAP mode tap user `whoami`
    sudo ip link set $TAP up
    sleep 0.5s
    # TODO: add to switch ip link set $1 master $switch

    n=$(( $i * 2 + 1 ))
    sudo ip addr add 192.168.7.$n/32 broadcast 192.168.7.255 dev $TAP
    sudo ip link set dev $TAP up

    dest=$(( $i * 2 + 2 ))
    sudo ip route add to 192.168.7.$dest dev $TAP

    # setup NAT for tap0 interface to have internet access in QEMU
    sudo iptables -A POSTROUTING -t nat -j MASQUERADE -s 192.168.7.$n/32
    sudo iptables -A POSTROUTING -t nat -j MASQUERADE -s 192.168.7.$dest/32
    sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
    sudo sh -c "echo 1 > /proc/sys/net/ipv4/conf/$TAP/proxy_arp"
    sudo iptables -P FORWARD ACCEPT
done
