@startuml

'left to right direction

title Components and Volume Provisioning

node "Compute Node" as computenode {
    frame "Host (Linux)" as host {
        package "Kubernetes (container)" {
            rectangle "**OIM CSI driver**" as oimdriver #LightBlue
            rectangle "**3rd-party CSI driver**" as otherdriver #LightBlue
            oimdriver -[hidden]> otherdriver
        }
    }

    frame "Accelerator Card (Linux)" as card {
        rectangle "SPDK vHost" as spdk
        rectangle "**OIM controller**" as controller #LightBlue {

        }

        spdk <- controller : vhost RPC API
    }

    host <-- card : **PCI**: virtio-blk, virtio-scsi
}

cloud "Control Plane" as controlplane {
    database etcd

    rectangle "OIM registry" as registry #LightBlue {
        interface Proxy #SteelBlue
        interface Registration #SteelBlue
        Proxy -[hidden]-> Registration
    }

    etcd -- registry
}

Proxy <- oimdriver : map volume XYZ on host ABC
Proxy -> controller : map volume XYZ

controlplane -[hidden]> computenode

database "Storage System" as storage

storage <-- otherdriver : provision
storage -- spdk : IO

@enduml
