@startuml
skinparam backgroundcolor transparent
skinparam ArrowColor #69489d
skinparam interface {
  borderColor #69489d
}
skinparam defaultFontName Arial
skinparam defaultFontSize 30
skinparam ArrowThickness 8

'left to right direction

node "Compute Node" as computenode {
    frame "Host (Linux)" as host {
        package "Kubernetes (container)" {
            rectangle "**OIM CSI driver**" as oimdriver #008bbf
            rectangle "**3rd-party CSI driver**" as otherdriver #40c4e0
            oimdriver -[hidden]> otherdriver
        }
    }

    frame "Accelerator Card (Linux)" as card {
        rectangle "SPDK vHost" as spdk #40c4e0
        rectangle "**OIM controller**" as controller #008bbf {

        }

        spdk <- controller : vhost RPC API
    }

    host <-- card : **PCI**: virtio-blk, virtio-scsi
}

cloud "Control Plane" as controlplane {
    database etcd #40c4e0

    rectangle "OIM registry" as registry #008bbf {
        interface Proxy #005a95
        interface Registration #005a95
        Proxy -[hidden]-> Registration
    }

    rectangle "oimctl" #008bbf

    etcd -- registry
    oimctl -- Registration
}


Proxy <- oimdriver : map volume XYZ on host ABC
Proxy -> controller : map volume XYZ

controlplane -[hidden]> computenode

database "Storage System" as storage  #40c4e0

storage <-- otherdriver : provision
storage <--> spdk


@enduml
