// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oim.proto

package oim

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterControllerRequest struct {
	// An identifier for the OIM controller which is unique
	// among all controllers connected to the OIM registry.
	ControllerId string `protobuf:"bytes,1,opt,name=controller_id,json=controllerId" json:"controller_id,omitempty"`
	// A string that can be used for grpc.Dial to connect
	// to the OIM controller.
	// See https://github.com/grpc/grpc/blob/master/doc/naming.md.
	// An empty string removes the database entry.
	Address              string   `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterControllerRequest) Reset()         { *m = RegisterControllerRequest{} }
func (m *RegisterControllerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterControllerRequest) ProtoMessage()    {}
func (*RegisterControllerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_oim_68d17cb2f1d81d6b, []int{0}
}
func (m *RegisterControllerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterControllerRequest.Unmarshal(m, b)
}
func (m *RegisterControllerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterControllerRequest.Marshal(b, m, deterministic)
}
func (dst *RegisterControllerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterControllerRequest.Merge(dst, src)
}
func (m *RegisterControllerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterControllerRequest.Size(m)
}
func (m *RegisterControllerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterControllerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterControllerRequest proto.InternalMessageInfo

func (m *RegisterControllerRequest) GetControllerId() string {
	if m != nil {
		return m.ControllerId
	}
	return ""
}

func (m *RegisterControllerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type RegisterControllerReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterControllerReply) Reset()         { *m = RegisterControllerReply{} }
func (m *RegisterControllerReply) String() string { return proto.CompactTextString(m) }
func (*RegisterControllerReply) ProtoMessage()    {}
func (*RegisterControllerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_oim_68d17cb2f1d81d6b, []int{1}
}
func (m *RegisterControllerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterControllerReply.Unmarshal(m, b)
}
func (m *RegisterControllerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterControllerReply.Marshal(b, m, deterministic)
}
func (dst *RegisterControllerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterControllerReply.Merge(dst, src)
}
func (m *RegisterControllerReply) XXX_Size() int {
	return xxx_messageInfo_RegisterControllerReply.Size(m)
}
func (m *RegisterControllerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterControllerReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterControllerReply proto.InternalMessageInfo

type MapVolumeRequest struct {
	// An identifier for the volume that must be unique
	// among all volumes mapped by the OIM controller.
	// All calls with the same identifier must have the
	// same parameters.
	VolumeId string `protobuf:"bytes,1,opt,name=volume_id,json=volumeId" json:"volume_id,omitempty"`
	// These parameters define how to access the volume.
	//
	// Types that are valid to be assigned to Params:
	//	*MapVolumeRequest_Malloc
	//	*MapVolumeRequest_Ceph
	Params               isMapVolumeRequest_Params `protobuf_oneof:"params"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MapVolumeRequest) Reset()         { *m = MapVolumeRequest{} }
func (m *MapVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*MapVolumeRequest) ProtoMessage()    {}
func (*MapVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_oim_68d17cb2f1d81d6b, []int{2}
}
func (m *MapVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapVolumeRequest.Unmarshal(m, b)
}
func (m *MapVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapVolumeRequest.Marshal(b, m, deterministic)
}
func (dst *MapVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapVolumeRequest.Merge(dst, src)
}
func (m *MapVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_MapVolumeRequest.Size(m)
}
func (m *MapVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MapVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MapVolumeRequest proto.InternalMessageInfo

type isMapVolumeRequest_Params interface {
	isMapVolumeRequest_Params()
}

type MapVolumeRequest_Malloc struct {
	Malloc *MallocParams `protobuf:"bytes,2,opt,name=malloc,oneof"`
}
type MapVolumeRequest_Ceph struct {
	Ceph *CephParams `protobuf:"bytes,3,opt,name=ceph,oneof"`
}

func (*MapVolumeRequest_Malloc) isMapVolumeRequest_Params() {}
func (*MapVolumeRequest_Ceph) isMapVolumeRequest_Params()   {}

func (m *MapVolumeRequest) GetParams() isMapVolumeRequest_Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *MapVolumeRequest) GetVolumeId() string {
	if m != nil {
		return m.VolumeId
	}
	return ""
}

func (m *MapVolumeRequest) GetMalloc() *MallocParams {
	if x, ok := m.GetParams().(*MapVolumeRequest_Malloc); ok {
		return x.Malloc
	}
	return nil
}

func (m *MapVolumeRequest) GetCeph() *CephParams {
	if x, ok := m.GetParams().(*MapVolumeRequest_Ceph); ok {
		return x.Ceph
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MapVolumeRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MapVolumeRequest_OneofMarshaler, _MapVolumeRequest_OneofUnmarshaler, _MapVolumeRequest_OneofSizer, []interface{}{
		(*MapVolumeRequest_Malloc)(nil),
		(*MapVolumeRequest_Ceph)(nil),
	}
}

func _MapVolumeRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MapVolumeRequest)
	// params
	switch x := m.Params.(type) {
	case *MapVolumeRequest_Malloc:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Malloc); err != nil {
			return err
		}
	case *MapVolumeRequest_Ceph:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ceph); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("MapVolumeRequest.Params has unexpected type %T", x)
	}
	return nil
}

func _MapVolumeRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MapVolumeRequest)
	switch tag {
	case 2: // params.malloc
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MallocParams)
		err := b.DecodeMessage(msg)
		m.Params = &MapVolumeRequest_Malloc{msg}
		return true, err
	case 3: // params.ceph
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CephParams)
		err := b.DecodeMessage(msg)
		m.Params = &MapVolumeRequest_Ceph{msg}
		return true, err
	default:
		return false, nil
	}
}

func _MapVolumeRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MapVolumeRequest)
	// params
	switch x := m.Params.(type) {
	case *MapVolumeRequest_Malloc:
		s := proto.Size(x.Malloc)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *MapVolumeRequest_Ceph:
		s := proto.Size(x.Ceph)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// For testing purposes a volume can be created in memory
// when it gets mapped for the first time. The data gets
// lost once the volume gets unmapped.
type MallocParams struct {
	// The desired size in bytes. Must be a multiple of 512.
	Size                 int64    `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MallocParams) Reset()         { *m = MallocParams{} }
func (m *MallocParams) String() string { return proto.CompactTextString(m) }
func (*MallocParams) ProtoMessage()    {}
func (*MallocParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_oim_68d17cb2f1d81d6b, []int{3}
}
func (m *MallocParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MallocParams.Unmarshal(m, b)
}
func (m *MallocParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MallocParams.Marshal(b, m, deterministic)
}
func (dst *MallocParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MallocParams.Merge(dst, src)
}
func (m *MallocParams) XXX_Size() int {
	return xxx_messageInfo_MallocParams.Size(m)
}
func (m *MallocParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MallocParams.DiscardUnknown(m)
}

var xxx_messageInfo_MallocParams proto.InternalMessageInfo

func (m *MallocParams) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

// Defines a Ceph block device. This is currently a placeholder
// to demonstrate how MapVolumeRequest.params will work.
type CephParams struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CephParams) Reset()         { *m = CephParams{} }
func (m *CephParams) String() string { return proto.CompactTextString(m) }
func (*CephParams) ProtoMessage()    {}
func (*CephParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_oim_68d17cb2f1d81d6b, []int{4}
}
func (m *CephParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CephParams.Unmarshal(m, b)
}
func (m *CephParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CephParams.Marshal(b, m, deterministic)
}
func (dst *CephParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CephParams.Merge(dst, src)
}
func (m *CephParams) XXX_Size() int {
	return xxx_messageInfo_CephParams.Size(m)
}
func (m *CephParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CephParams.DiscardUnknown(m)
}

var xxx_messageInfo_CephParams proto.InternalMessageInfo

func (m *CephParams) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

// The reply tells the caller enough about the mapped volume
// to access it.
type MapVolumeReply struct {
	// The PCI address of the controller which provides
	// access to the volume.
	PciAddress string `protobuf:"bytes,1,opt,name=pci_address,json=pciAddress" json:"pci_address,omitempty"`
	// The SCSI target and LUN in the format
	// x:y without extra zeros.
	// Only set for SCSI controllers.
	ScsiDevice           string   `protobuf:"bytes,2,opt,name=scsi_device,json=scsiDevice" json:"scsi_device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapVolumeReply) Reset()         { *m = MapVolumeReply{} }
func (m *MapVolumeReply) String() string { return proto.CompactTextString(m) }
func (*MapVolumeReply) ProtoMessage()    {}
func (*MapVolumeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_oim_68d17cb2f1d81d6b, []int{5}
}
func (m *MapVolumeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapVolumeReply.Unmarshal(m, b)
}
func (m *MapVolumeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapVolumeReply.Marshal(b, m, deterministic)
}
func (dst *MapVolumeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapVolumeReply.Merge(dst, src)
}
func (m *MapVolumeReply) XXX_Size() int {
	return xxx_messageInfo_MapVolumeReply.Size(m)
}
func (m *MapVolumeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MapVolumeReply.DiscardUnknown(m)
}

var xxx_messageInfo_MapVolumeReply proto.InternalMessageInfo

func (m *MapVolumeReply) GetPciAddress() string {
	if m != nil {
		return m.PciAddress
	}
	return ""
}

func (m *MapVolumeReply) GetScsiDevice() string {
	if m != nil {
		return m.ScsiDevice
	}
	return ""
}

type UnmapVolumeRequest struct {
	// The volume ID that was used when mapping the volume.
	VolumeId             string   `protobuf:"bytes,1,opt,name=volume_id,json=volumeId" json:"volume_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnmapVolumeRequest) Reset()         { *m = UnmapVolumeRequest{} }
func (m *UnmapVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*UnmapVolumeRequest) ProtoMessage()    {}
func (*UnmapVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_oim_68d17cb2f1d81d6b, []int{6}
}
func (m *UnmapVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnmapVolumeRequest.Unmarshal(m, b)
}
func (m *UnmapVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnmapVolumeRequest.Marshal(b, m, deterministic)
}
func (dst *UnmapVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnmapVolumeRequest.Merge(dst, src)
}
func (m *UnmapVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_UnmapVolumeRequest.Size(m)
}
func (m *UnmapVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnmapVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnmapVolumeRequest proto.InternalMessageInfo

func (m *UnmapVolumeRequest) GetVolumeId() string {
	if m != nil {
		return m.VolumeId
	}
	return ""
}

type UnmapVolumeReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnmapVolumeReply) Reset()         { *m = UnmapVolumeReply{} }
func (m *UnmapVolumeReply) String() string { return proto.CompactTextString(m) }
func (*UnmapVolumeReply) ProtoMessage()    {}
func (*UnmapVolumeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_oim_68d17cb2f1d81d6b, []int{7}
}
func (m *UnmapVolumeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnmapVolumeReply.Unmarshal(m, b)
}
func (m *UnmapVolumeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnmapVolumeReply.Marshal(b, m, deterministic)
}
func (dst *UnmapVolumeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnmapVolumeReply.Merge(dst, src)
}
func (m *UnmapVolumeReply) XXX_Size() int {
	return xxx_messageInfo_UnmapVolumeReply.Size(m)
}
func (m *UnmapVolumeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnmapVolumeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnmapVolumeReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RegisterControllerRequest)(nil), "oim.v0.RegisterControllerRequest")
	proto.RegisterType((*RegisterControllerReply)(nil), "oim.v0.RegisterControllerReply")
	proto.RegisterType((*MapVolumeRequest)(nil), "oim.v0.MapVolumeRequest")
	proto.RegisterType((*MallocParams)(nil), "oim.v0.MallocParams")
	proto.RegisterType((*CephParams)(nil), "oim.v0.CephParams")
	proto.RegisterType((*MapVolumeReply)(nil), "oim.v0.MapVolumeReply")
	proto.RegisterType((*UnmapVolumeRequest)(nil), "oim.v0.UnmapVolumeRequest")
	proto.RegisterType((*UnmapVolumeReply)(nil), "oim.v0.UnmapVolumeReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Registry service

type RegistryClient interface {
	// Adds a new entry to the registry DB or overwrites
	// an existing one.
	RegisterController(ctx context.Context, in *RegisterControllerRequest, opts ...grpc.CallOption) (*RegisterControllerReply, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) RegisterController(ctx context.Context, in *RegisterControllerRequest, opts ...grpc.CallOption) (*RegisterControllerReply, error) {
	out := new(RegisterControllerReply)
	err := grpc.Invoke(ctx, "/oim.v0.Registry/RegisterController", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Registry service

type RegistryServer interface {
	// Adds a new entry to the registry DB or overwrites
	// an existing one.
	RegisterController(context.Context, *RegisterControllerRequest) (*RegisterControllerReply, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_RegisterController_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterControllerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RegisterController(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oim.v0.Registry/RegisterController",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RegisterController(ctx, req.(*RegisterControllerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oim.v0.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterController",
			Handler:    _Registry_RegisterController_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oim.proto",
}

// Client API for Controller service

type ControllerClient interface {
	// Makes a volume available via the accelerator hardware.
	// The call must be idempotent: when a caller is unsure whether
	// a call was executed or what the result was, MapVolume
	// can be called again and will succeed without changing
	// anything.
	MapVolume(ctx context.Context, in *MapVolumeRequest, opts ...grpc.CallOption) (*MapVolumeReply, error)
	// Removes access to the volume.
	// Also idempotent.
	UnmapVolume(ctx context.Context, in *UnmapVolumeRequest, opts ...grpc.CallOption) (*UnmapVolumeReply, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) MapVolume(ctx context.Context, in *MapVolumeRequest, opts ...grpc.CallOption) (*MapVolumeReply, error) {
	out := new(MapVolumeReply)
	err := grpc.Invoke(ctx, "/oim.v0.Controller/MapVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) UnmapVolume(ctx context.Context, in *UnmapVolumeRequest, opts ...grpc.CallOption) (*UnmapVolumeReply, error) {
	out := new(UnmapVolumeReply)
	err := grpc.Invoke(ctx, "/oim.v0.Controller/UnmapVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Controller service

type ControllerServer interface {
	// Makes a volume available via the accelerator hardware.
	// The call must be idempotent: when a caller is unsure whether
	// a call was executed or what the result was, MapVolume
	// can be called again and will succeed without changing
	// anything.
	MapVolume(context.Context, *MapVolumeRequest) (*MapVolumeReply, error)
	// Removes access to the volume.
	// Also idempotent.
	UnmapVolume(context.Context, *UnmapVolumeRequest) (*UnmapVolumeReply, error)
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_MapVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).MapVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oim.v0.Controller/MapVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).MapVolume(ctx, req.(*MapVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_UnmapVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmapVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UnmapVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/oim.v0.Controller/UnmapVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UnmapVolume(ctx, req.(*UnmapVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "oim.v0.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MapVolume",
			Handler:    _Controller_MapVolume_Handler,
		},
		{
			MethodName: "UnmapVolume",
			Handler:    _Controller_UnmapVolume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oim.proto",
}

func init() { proto.RegisterFile("oim.proto", fileDescriptor_oim_68d17cb2f1d81d6b) }

var fileDescriptor_oim_68d17cb2f1d81d6b = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x6b, 0x52, 0x4c, 0x3c, 0x29, 0xa8, 0x1a, 0xa1, 0xe2, 0x1a, 0x89, 0xc2, 0xc2, 0xa1,
	0x27, 0x17, 0xc2, 0x03, 0x20, 0x5a, 0x90, 0xe8, 0xa1, 0x12, 0xb2, 0x04, 0x87, 0x5c, 0x22, 0x67,
	0x3d, 0x49, 0x56, 0x5a, 0x67, 0x97, 0x5d, 0x27, 0xc8, 0xbc, 0x06, 0x3c, 0x30, 0xf2, 0xda, 0x8e,
	0x1d, 0x25, 0x20, 0xf5, 0xe6, 0xfd, 0xe7, 0xf3, 0x3f, 0x3b, 0xff, 0x2c, 0x04, 0x4a, 0xe4, 0xb1,
	0x36, 0xaa, 0x50, 0xe8, 0x57, 0x9f, 0x9b, 0xb7, 0xd1, 0x8b, 0x85, 0x52, 0x0b, 0x49, 0x57, 0x4e,
	0x9d, 0xad, 0xe7, 0x57, 0x3f, 0x4d, 0xaa, 0x35, 0x19, 0x5b, 0x73, 0x6c, 0x02, 0xe7, 0x09, 0x2d,
	0x84, 0x2d, 0xc8, 0xdc, 0xa8, 0x55, 0x61, 0x94, 0x94, 0x64, 0x12, 0xfa, 0xb1, 0x26, 0x5b, 0xe0,
	0x6b, 0x78, 0xcc, 0xb7, 0xe2, 0x54, 0x64, 0xa1, 0xf7, 0xd2, 0xbb, 0x0c, 0x92, 0x93, 0x4e, 0xbc,
	0xcd, 0x30, 0x84, 0x47, 0x69, 0x96, 0x19, 0xb2, 0x36, 0x7c, 0xe0, 0xca, 0xed, 0x91, 0x9d, 0xc3,
	0xb3, 0x43, 0xde, 0x5a, 0x96, 0xec, 0xb7, 0x07, 0xa7, 0x77, 0xa9, 0xfe, 0xae, 0xe4, 0x3a, 0xa7,
	0xb6, 0xdd, 0x73, 0x08, 0x36, 0x4e, 0xe8, 0x5a, 0x0d, 0x6b, 0xe1, 0x36, 0xc3, 0x18, 0xfc, 0x3c,
	0x95, 0x52, 0x71, 0xd7, 0x65, 0x34, 0x7e, 0x1a, 0xd7, 0x13, 0xc6, 0x77, 0x4e, 0xfd, 0x9a, 0x9a,
	0x34, 0xb7, 0x5f, 0x8e, 0x92, 0x86, 0xc2, 0x4b, 0x38, 0xe6, 0xa4, 0x97, 0xe1, 0xc0, 0xd1, 0xd8,
	0xd2, 0x37, 0xa4, 0x97, 0x5b, 0xd6, 0x11, 0xd7, 0x43, 0xf0, 0xb5, 0x53, 0x18, 0x83, 0x93, 0xbe,
	0x1b, 0x22, 0x1c, 0x5b, 0xf1, 0x8b, 0xdc, 0x5d, 0x06, 0x89, 0xfb, 0x66, 0x6f, 0x00, 0x3a, 0x0f,
	0x3c, 0x03, 0xdf, 0x12, 0x37, 0x54, 0x34, 0xf7, 0x6d, 0x4e, 0x2c, 0x81, 0x27, 0xbd, 0xf1, 0xb4,
	0x2c, 0xf1, 0x02, 0x46, 0x9a, 0x8b, 0x69, 0x1b, 0x55, 0x8d, 0x83, 0xe6, 0xe2, 0x63, 0xad, 0x54,
	0x80, 0xe5, 0x56, 0x4c, 0x33, 0xda, 0x08, 0x4e, 0x4d, 0x96, 0x50, 0x49, 0x9f, 0x9c, 0xc2, 0xde,
	0x01, 0x7e, 0x5b, 0xe5, 0xf7, 0x09, 0x8d, 0x21, 0x9c, 0xee, 0xfc, 0xa2, 0x65, 0x39, 0x9e, 0xc3,
	0xb0, 0xde, 0x8a, 0x29, 0x71, 0x02, 0xb8, 0xbf, 0x21, 0x7c, 0xd5, 0x86, 0xf5, 0xcf, 0x97, 0x11,
	0x5d, 0xfc, 0x0f, 0xa9, 0x16, 0x7c, 0x34, 0xfe, 0xe3, 0x01, 0xf4, 0x4c, 0x3f, 0x40, 0xb0, 0x4d,
	0x04, 0xc3, 0x6e, 0x79, 0xbb, 0xe3, 0x44, 0x67, 0x07, 0x2a, 0xce, 0x0f, 0x3f, 0xc3, 0xa8, 0x37,
	0x0b, 0x46, 0x2d, 0xb8, 0x9f, 0x49, 0x14, 0x1e, 0xac, 0x39, 0x9b, 0xeb, 0x87, 0x93, 0x81, 0x12,
	0xf9, 0xcc, 0x77, 0xcf, 0xff, 0xfd, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xb5, 0x1e, 0x89,
	0x33, 0x03, 0x00, 0x00,
}
